### ISSUE TITLE
After reading your work, I think it is a very meaningful work!  When are you going to open source your code? 

### ISSUE THREAD

**Issue by eternalld** [hustvl/BoxTeacher#2]

**Comment by wondervictor** [comment]
Hi @EternalLD, thanks for your recognition and interest! We are planning to release the code & models at the end of this year or the beginning of the next year~
If you have any questions about BoxTeacher, please feel free to ask.

**Comment by VikasRajashekar** [comment]
Any update on code releasing?

**Comment by wondervictor** [comment]
Hi all, code & models of BoxTeacher have been released. Thanks for your interest❤️.
