### ISSUE TITLE
AttributeError: 'BoxTeacher' object has no attribute 'module

### ISSUE THREAD

**Issue by XJWang628** [hustvl/BoxTeacher#3]
Hi, I encountered "AttributeError: 'BoxTeacher' object has no attribute 'module'" while training BoXTeacher on a single 3090, is there any way to solve it?
![image](https://user-images.githubusercontent.com/74861454/233996096-d1afe9e5-0aa6-4644-a9a9-a7f56639b6f7.png)

**Comment by Huster-Hq** [comment]
Hi, my bug is "'FCOS' object has no attribute 'forward_test'".

**Comment by Huster-Hq** [comment]
> 嗨，我在单个 3090 上训练 BoXTeacher 时遇到了“属性错误：'BoxTeacher' 对象没有属性'模块'”，有什么办法可以解决吗？ ![图像](https://user-images.githubusercontent.com/74861454/233996096-d1afe9e5-0aa6-4644-a9a9-a7f56639b6f7.png)
You can find the code where the error occurred and remove the '.module '， I solved the bug with this method。

**Comment by wondervictor** [comment]
Thank @Huster-Hq  for solving this issue. As for that FCOS does not have "forward_test", you might need to use the modified version of FCOS in this repo, in which we have add "forward_test".

**Comment by mmliu202210** [comment]
> 感谢您解决此问题。至于 FCOS 没有 “forward_test”，您可能需要在此存储库中使用修改后的 FCOS 版本，我们在其中添加了 “forward_test”。

I'm also experiencing this problem, can you provide a modified version of FCOS please?
